<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.marcoaga02</groupId>
  <artifactId>car-rental-manager</artifactId>
  <version>0.0.1-SNAPSHOT</version>

  <name>car-rental-manager</name>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>11</maven.compiler.source>
    <maven.compiler.target>11</maven.compiler.target>
    <maven.compiler.plugin.version>3.8.0</maven.compiler.plugin.version>

    <junit.jupiter.version>5.14.4</junit.jupiter.version>
    <junit.4.version>4.13.2</junit.4.version>
    <assertj.version>3.27.7</assertj.version>
    <assertj.swing.version>3.17.1</assertj.swing.version>
    <jacoco.version>0.8.15</jacoco.version>
    <pitest.version>1.25.7</pitest.version>
    <coveralls.version>5.1.0</coveralls.version>
    <mockito.version>5.23.0</mockito.version>
    <maven.surefire.version>3.5.6</maven.surefire.version>
    <jakarta.persistence.api.version>3.1.0</jakarta.persistence.api.version>
    <testcontainers.version>1.21.4</testcontainers.version>
    <hibernate.version>6.6.54.Final</hibernate.version>
    <postgres.version>42.7.13</postgres.version>
    <picocli.version>4.7.7</picocli.version>

    <commons.lang3.version>3.20.0</commons.lang3.version>
    <pitest.junit5.plugin.version>1.2.3</pitest.junit5.plugin.version>

    <sonar.coverage.exclusions>
      **/model/Car.java,**/model/Customer.java,**/model/Rental.java,**/viewmodel/*.*, **/main/*.*</sonar.coverage.exclusions>
    <sonar.cpd.exclusions>**/model/**,**/viewmodel/**</sonar.cpd.exclusions>

    <sonar.tests>
      ${project.basedir}/src/test/java,
    </sonar.tests>

    <sonar.junit.reportPaths>
      ${project.build.directory}/surefire-reports
    </sonar.junit.reportPaths>

    <!-- At least one assertion (GUI tests) -->
    <sonar.issue.ignore.multicriteria.e15.ruleKey>
      java:S2699
    </sonar.issue.ignore.multicriteria.e15.ruleKey>
  </properties>

  <dependencies>
    <dependency>
      <groupId>jakarta.persistence</groupId>
      <artifactId>jakarta.persistence-api</artifactId>
      <version>${jakarta.persistence.api.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-lang3</artifactId>
      <version>${commons.lang3.version}</version>
    </dependency>
    <dependency>
      <groupId>org.hibernate.orm</groupId>
      <artifactId>hibernate-core</artifactId>
      <version>${hibernate.version}</version>
    </dependency>
    <dependency>
      <groupId>org.postgresql</groupId>
      <artifactId>postgresql</artifactId>
      <version>${postgres.version}</version>
    </dependency>
    <dependency>
      <groupId>info.picocli</groupId>
      <artifactId>picocli</artifactId>
      <version>${picocli.version}</version>
    </dependency>

    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <version>${junit.jupiter.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.vintage</groupId>
      <artifactId>junit-vintage-engine</artifactId>
      <version>${junit.jupiter.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>${junit.4.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.assertj</groupId>
      <artifactId>assertj-core</artifactId>
      <version>${assertj.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.assertj</groupId>
      <artifactId>assertj-swing-junit</artifactId>
      <version>${assertj.swing.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-core</artifactId>
      <version>${mockito.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-junit-jupiter</artifactId>
      <version>${mockito.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.testcontainers</groupId>
      <artifactId>testcontainers</artifactId>
      <version>${testcontainers.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.testcontainers</groupId>
      <artifactId>junit-jupiter</artifactId>
      <version>${testcontainers.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.testcontainers</groupId>
      <artifactId>postgresql</artifactId>
      <version>${testcontainers.version}</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.jacoco</groupId>
          <artifactId>jacoco-maven-plugin</artifactId>
          <version>${jacoco.version}</version>
          <configuration>
            <excludes>
              <exclude>**/model/Car.class</exclude>
              <exclude>**/model/Customer.class</exclude>
              <exclude>**/model/Rental.class</exclude>
              <exclude>**/viewmodel/*.*</exclude>
              <exclude>**/main/*.*</exclude>
            </excludes>
          </configuration>
          <executions>
            <execution>
              <goals>
                <goal>prepare-agent</goal>
                <goal>report</goal>
              </goals>
            </execution>
            <execution>
              <id>jacoco-check</id>
              <goals>
                <goal>check</goal>
              </goals>
              <configuration>
                <rules>
                  <rule>
                    <element>PACKAGE</element>
                    <limits>
                      <limit>
                        <counter>LINE</counter>
                        <value>COVEREDRATIO</value>
                        <minimum>1</minimum>
                      </limit>
                    </limits>
                  </rule>
                </rules>
              </configuration>
            </execution>
          </executions>
        </plugin>
        <plugin>
          <groupId>org.pitest</groupId>
          <artifactId>pitest-maven</artifactId>
          <version>${pitest.version}</version>
          <dependencies>
            <dependency>
              <groupId>org.pitest</groupId>
              <artifactId>pitest-junit5-plugin</artifactId>
              <version>${pitest.junit5.plugin.version}</version>
            </dependency>
          </dependencies>
          <configuration>
            <targetClasses>
              <param>com.marcoaga02.carrentalmanager.mapper.*</param>
              <param>com.marcoaga02.carrentalmanager.service.*</param>
              <param>com.marcoaga02.carrentalmanager.controller.*</param>
            </targetClasses>
            <targetTests>
              <param>com.marcoaga02.carrentalmanager.mapper.*</param>
              <param>com.marcoaga02.carrentalmanager.service.*</param>
              <param>com.marcoaga02.carrentalmanager.controller.*</param>
            </targetTests>
            <mutators>
              <mutator>DEFAULTS</mutator>
            </mutators>
            <mutationThreshold>100</mutationThreshold>
          </configuration>
        </plugin>
        <plugin>
          <groupId>com.github.hazendaz.maven</groupId>
          <artifactId>coveralls-maven-plugin</artifactId>
          <version>${coveralls.version}</version>
          <configuration>
            <repoToken>${env.COVERALLS_REPO_TOKEN}</repoToken>
          </configuration>
        </plugin>
        <plugin>
          <artifactId>maven-surefire-report-plugin</artifactId>
          <version>${maven.surefire.version}</version>
        </plugin>
        <plugin>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>${maven.surefire.version}</version>
        </plugin>
      </plugins>
    </pluginManagement>

    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>${maven.compiler.plugin.version}</version>
        <configuration>
          <source>${maven.compiler.source}</source>
          <target>${maven.compiler.target}</target>
        </configuration>
      </plugin>
    </plugins>
  </build>

  <profiles>
    <profile>
      <id>jacoco</id>
      <activation>
        <property>
          <name>!skipCoverage</name>
        </property>
      </activation>
      <build>
        <plugins>
          <plugin>
            <groupId>org.jacoco</groupId>
            <artifactId>jacoco-maven-plugin</artifactId>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>mutation-testing</id>
      <build>
        <plugins>
          <plugin>
            <groupId>org.pitest</groupId>
            <artifactId>pitest-maven</artifactId>
            <executions>
              <execution>
                <goals>
                  <goal>mutationCoverage</goal>
                </goals>
                <phase>verify</phase>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>coveralls</id>
      <build>
        <plugins>
          <plugin>
            <groupId>org.jacoco</groupId>
            <artifactId>jacoco-maven-plugin</artifactId>
          </plugin>
          <plugin>
            <groupId>com.github.hazendaz.maven</groupId>
            <artifactId>coveralls-maven-plugin</artifactId>
            <executions>
              <execution>
                <phase>verify</phase>
                <goals>
                  <goal>report</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
</project>
